version: '3.8'
services:
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80
    links:
      - mysql:db

  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./var/cache/mysql:/var/lib/mysql